name: Send email
on:
  schedule:
    - cron: "0 5 */3 * *"  # Every 3 days at 05:00 UTC
  workflow_dispatch:       # allow manual trigger from GitHub 

permissions:
  contents: write

jobs:
  send_email:
    runs-on: ubuntu-latest
      
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" 

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # allows push with GITHUB_TOKEN
          fetch-depth: 0              # fetch full history (needed for push)

      - name: Fetch ISS data
        run: |
          # curl -s "https://celestrak.org/NORAD/elements/gp.php?GROUP=stations&FORMAT=json" -o ISS.csv

      - name: Commit and push updated ISS.csv
        id: commit_csv
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add ISS.csv

          # Only commit if there are changes to the CSV file 
          if ! git diff --cached --quiet; then
          git commit -m "Update TLE file"
          git pull --rebase origin main
          git push -f origin main
          else
            echo "ISS.csv unchanged — skipping commit and push."
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send email
        run: python send_email.py
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
